CREATE TABLE `inventoryMovementSnapshots` (
	`id` int AUTO_INCREMENT NOT NULL,
	`branchId` int,
	`costCenterCode` varchar(80) NOT NULL,
	`periodStart` timestamp NOT NULL,
	`periodEnd` timestamp NOT NULL,
	`itemCode` varchar(80) NOT NULL,
	`itemName` varchar(240) NOT NULL,
	`availableQuantity` decimal(16,3) NOT NULL DEFAULT '0',
	`availableCost` decimal(16,2) NOT NULL DEFAULT '0',
	`openingQuantity` decimal(16,3) NOT NULL DEFAULT '0',
	`openingCost` decimal(16,2) NOT NULL DEFAULT '0',
	`receivedQuantity` decimal(16,3) NOT NULL DEFAULT '0',
	`receivedCost` decimal(16,2) NOT NULL DEFAULT '0',
	`issuedQuantity` decimal(16,3) NOT NULL DEFAULT '0',
	`transferQuantity` decimal(16,3) NOT NULL DEFAULT '0',
	`adjustmentQuantity` decimal(16,3) NOT NULL DEFAULT '0',
	`unreceivedQuantity` decimal(16,3) NOT NULL DEFAULT '0',
	`netReceivedQuantity` decimal(16,3) NOT NULL DEFAULT '0',
	`salesQuantity` decimal(16,3) NOT NULL DEFAULT '0',
	`salesValue` decimal(16,2) NOT NULL DEFAULT '0',
	`salesCost` decimal(16,2) NOT NULL DEFAULT '0',
	`returnQuantity` decimal(16,3) NOT NULL DEFAULT '0',
	`returnValue` decimal(16,2) NOT NULL DEFAULT '0',
	`returnCost` decimal(16,2) NOT NULL DEFAULT '0',
	`netQuantity` decimal(16,3) NOT NULL DEFAULT '0',
	`netSales` decimal(16,2) NOT NULL DEFAULT '0',
	`netCost` decimal(16,2) NOT NULL DEFAULT '0',
	`profitabilityRate` decimal(10,4),
	`grossMargin` decimal(16,2),
	`sellingRate` decimal(10,4),
	`stockAgeDays` decimal(12,2),
	`dailySellingRate` decimal(12,4),
	`expectedStockoutDays` decimal(12,2),
	`sourceFileName` varchar(255) NOT NULL,
	`sourceSheet` varchar(120) NOT NULL,
	`importedBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `inventoryMovementSnapshots_id` PRIMARY KEY(`id`),
	CONSTRAINT `inventory_item_center_period_unique` UNIQUE(`costCenterCode`,`periodStart`,`periodEnd`,`itemCode`)
);
