import { useMemo, useState } from "react";
import type { ReactNode } from "react";
import { ArrowDownLeft, ArrowUpLeft, BarChart3, CircleAlert, Database, TrendingDown, TrendingUp } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { ResponsiveContainer, LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, BarChart, Bar } from "recharts";

type TrendRow = { period: string; netSales?: number | string; revenue?: number | string; netCost?: number | string; expenses?: number | string; netProfit?: number | string };
type BranchRow = { id: number; name: string; operationalType?: string; currentRevenue?: number | string | null; currentProfit?: number | string | null; currentExpenses?: number | string; operatingExpenses?: number | string; profitChangePercent?: number | string | null };
type Props = { data?: { financialTrend?: TrendRow[]; financialByBranch?: BranchRow[]; financialCoverage?: { rate: number | null; centersWithData: number; expectedCenters: number; period: string; missingCenters?: Array<{ id: number; name: string }> } }; loading?: boolean };

const num = (value: number | string | null | undefined) => Number(value ?? 0);
const money = (value: number) => new Intl.NumberFormat("ar-SA", { maximumFractionDigits: 0 }).format(value);

export default function ExecutiveFinanceCommandCenter({ data, loading }: Props) {
  const [scope, setScope] = useState<"all" | "sales" | "nonSales">("all");
  const trend = useMemo(() => (data?.financialTrend ?? []).map((row) => ({ ...row, label: row.period, netSales: num(row.netSales ?? row.revenue), netCost: num(row.netCost), expenses: num(row.expenses), netProfit: num(row.netProfit) })), [data?.financialTrend]);
  const branches = useMemo(() => (data?.financialByBranch ?? []).filter((row) => scope === "all" || (scope === "sales" ? row.operationalType !== "warehouse" && row.operationalType !== "representative" : row.operationalType === "warehouse" || row.operationalType === "representative")).sort((a, b) => num(b.currentProfit) - num(a.currentProfit)), [data?.financialByBranch, scope]);
  const latest = trend.at(-1);
  const previous = trend.at(-2);
  const profitChange = latest && previous ? latest.netProfit - previous.netProfit : null;
  const margin = latest && latest.netSales ? (latest.netProfit / latest.netSales) * 100 : null;
  const topBranches = branches.slice(0, 5);
  const attention = branches.filter((row) => num(row.currentProfit) < 0 || (num(row.currentRevenue) > 0 && (num(row.currentProfit) / num(row.currentRevenue)) * 100 < 5)).slice(0, 5);

  if (loading) return <section className="mb-5 rounded-2xl border border-[#dce9dd] bg-white p-5 text-sm text-[#6f8577]">جاري تجهيز لوحة المدير من البيانات الفعلية...</section>;
  return <section className="mb-5 rounded-2xl border border-[#dce9dd] bg-[#f8fcf8] p-5 shadow-[0_8px_24px_rgba(39,70,48,0.06)]" aria-label="لوحة المدير المالية والتنفيذية">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#174c3d] text-white"><BarChart3 className="h-5 w-5" /></div><div><h2 className="text-base font-bold text-[#174c3d]">لوحة قرار المدير</h2><p className="mt-1 text-xs text-[#6f8577]">ما الذي يحتاج قرارًا أو متابعة الآن؟</p></div></div></div><div className="flex flex-wrap gap-2"><button type="button" onClick={() => setScope("all")} className={`rounded-lg px-3 py-1.5 text-xs ${scope === "all" ? "bg-[#174c3d] text-white" : "bg-white text-[#52705d]"}`}>كل المراكز</button><button type="button" onClick={() => setScope("sales")} className={`rounded-lg px-3 py-1.5 text-xs ${scope === "sales" ? "bg-[#174c3d] text-white" : "bg-white text-[#52705d]"}`}>المراكز البيعية</button><button type="button" onClick={() => setScope("nonSales")} className={`rounded-lg px-3 py-1.5 text-xs ${scope === "nonSales" ? "bg-[#174c3d] text-white" : "bg-white text-[#52705d]"}`}>غير البيعية</button></div></div>
    <div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="صافي المبيعات" value={latest ? `${money(latest.netSales)} ر.س` : "—"} detail={latest?.period ?? "لا توجد فترة"} icon={<TrendingUp className="h-4 w-4" />} /><Metric label="صافي هامش الربح" value={margin === null ? "—" : `${margin.toFixed(1)}%`} detail={profitChange === null ? "لا توجد مقارنة سابقة" : `${profitChange >= 0 ? "+" : ""}${money(profitChange)} ر.س عن السابق`} icon={profitChange !== null && profitChange < 0 ? <TrendingDown className="h-4 w-4" /> : <ArrowUpLeft className="h-4 w-4" />} /><Metric label="صافي التكلفة" value={latest ? `${money(latest.netCost)} ر.س` : "—"} detail="بعد استبعاد الأرصدة التراكمية" icon={<Database className="h-4 w-4" />} /><Metric label="اكتمال البيانات" value={data?.financialCoverage?.rate == null ? "—" : `${data.financialCoverage.rate}%`} detail={data?.financialCoverage ? `${data.financialCoverage.centersWithData} من ${data.financialCoverage.expectedCenters} مركزًا` : "لا توجد تغطية"} icon={<CircleAlert className="h-4 w-4" />} /></div>
    <div className="mt-4 grid gap-4 xl:grid-cols-[1.35fr_1fr]"><Card className="border-[#e1ebe2] bg-white"><CardHeader className="pb-2"><CardTitle className="text-sm text-[#315542]">اتجاه صافي المبيعات والربح عبر الزمن</CardTitle></CardHeader><CardContent className="h-64"><ResponsiveContainer width="100%" height="100%"><LineChart data={trend}><CartesianGrid strokeDasharray="3 3" stroke="#edf1ed" /><XAxis dataKey="label" tick={{ fontSize: 10 }} /><YAxis tick={{ fontSize: 10 }} /><Tooltip formatter={(value: number) => `${money(value)} ر.س`} /><Line type="monotone" dataKey="netSales" name="صافي المبيعات" stroke="#2d7d58" strokeWidth={3} dot={{ r: 3 }} /><Line type="monotone" dataKey="netProfit" name="صافي الربح" stroke="#c48635" strokeWidth={3} dot={{ r: 3 }} /></LineChart></ResponsiveContainer></CardContent></Card><Card className="border-[#e1ebe2] bg-white"><CardHeader className="pb-2"><CardTitle className="text-sm text-[#315542]">ترتيب المراكز حسب صافي الربح</CardTitle></CardHeader><CardContent className="h-64"><ResponsiveContainer width="100%" height="100%"><BarChart data={topBranches} layout="vertical" margin={{ left: 20, right: 10 }}><CartesianGrid strokeDasharray="3 3" stroke="#edf1ed" /><XAxis type="number" tick={{ fontSize: 10 }} /><YAxis type="category" dataKey="name" width={90} tick={{ fontSize: 9 }} /><Tooltip formatter={(value: number) => `${money(value)} ر.س`} /><Bar dataKey="currentProfit" name="صافي الربح" fill="#2d7d58" radius={[0, 5, 5, 0]} /></BarChart></ResponsiveContainer></CardContent></Card></div>
    <div className="mt-4 grid gap-4 lg:grid-cols-2"><div className="rounded-xl border border-[#e1ebe2] bg-white p-4"><div className="flex items-center justify-between"><h3 className="text-sm font-bold text-[#315542]">اكتمال البيانات</h3><Badge variant="outline" className="text-[10px]">{data?.financialCoverage?.period ?? "الفترة الحالية"}</Badge></div><Progress className="mt-3 h-2" value={data?.financialCoverage?.rate ?? 0} /><p className="mt-2 text-xs text-[#6f8577]">تُحسب النسبة من المراكز التي لديها لقطة مالية فعلية فقط.</p>{(data?.financialCoverage?.missingCenters?.length ?? 0) > 0 && <p className="mt-2 text-xs text-[#a45b4e]">تحتاج مراجعة: {data?.financialCoverage?.missingCenters?.slice(0, 3).map((item) => item.name).join("، ")}</p>}</div><div className="rounded-xl border border-[#f0d9cf] bg-[#fffaf7] p-4"><div className="flex items-center gap-2"><CircleAlert className="h-4 w-4 text-[#a45b4e]" /><h3 className="text-sm font-bold text-[#7d4d42]">استثناءات تتطلب قرارًا</h3></div>{attention.length ? <div className="mt-3 space-y-2">{attention.map((row) => <div key={row.id} className="flex items-center justify-between gap-2 text-xs"><span className="truncate text-[#6d5d57]">{row.name}</span><span className="font-bold text-[#a45b4e]">{num(row.currentProfit) < 0 ? "خسارة" : "هامش منخفض"}</span></div>)}</div> : <p className="mt-3 text-xs text-[#6f8577]">لا توجد استثناءات واضحة في البيانات المتاحة.</p>}</div></div>
    <p className="mt-3 flex items-center gap-1 text-[10px] text-[#89948b]"><ArrowDownLeft className="h-3 w-3" /> تُعرض الأرقام من الفترة المتاحة فعليًا، وتُستبعد المراكز غير البيعية من فلتر المراكز البيعية.</p>
  </section>;
}

function Metric({ label, value, detail, icon }: { label: string; value: string; detail: string; icon: ReactNode }) { return <div className="rounded-xl border border-white bg-white p-3"><div className="flex items-center justify-between text-[#52705d]"><span className="text-xs font-semibold">{label}</span>{icon}</div><p className="mt-2 text-xl font-bold text-[#174c3d]">{value}</p><p className="mt-1 text-[10px] text-[#89948b]">{detail}</p></div>; }
