import { useMemo, useState } from "react";
import { AlertTriangle, Download, FileText, Filter, RefreshCw, Search } from "lucide-react";
import * as XLSX from "xlsx";
import jsPDF from "jspdf";
import { trpc } from "@/lib/trpc";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";

const formatLabels: Record<string, string> = { csv: "CSV", excel: "Excel", pdf: "PDF" };
const statusLabels: Record<string, string> = { started: "بدأت", success: "نجحت", failed: "فشلت" };

export function ExportAuditView() {
  const [format, setFormat] = useState("all");
  const [status, setStatus] = useState("all");
  const [actorQuery, setActorQuery] = useState("");
  const [from, setFrom] = useState("");
  const [to, setTo] = useState("");
  const query = trpc.exports.list.useQuery({ format: format as "csv" | "excel" | "pdf" | "all", status: status as "started" | "success" | "failed" | "all", from: from || undefined, to: to || undefined }, { staleTime: 15_000 });
  const rows = useMemo(() => (query.data?.rows ?? []).filter((row) => !actorQuery.trim() || row.actorName.toLocaleLowerCase("ar").includes(actorQuery.trim().toLocaleLowerCase("ar"))), [actorQuery, query.data?.rows]);
  const exportLog = trpc.exports.log.useMutation();
  const canExport = trpc.exports.canExportAudit.useQuery();
  const authorizeExport = trpc.exports.authorizeAuditExport.useMutation();
  const thresholdQuery = trpc.preferences.getExportFailureThreshold.useQuery();
  const saveThreshold = trpc.preferences.saveExportFailureThreshold.useMutation({ onSuccess: () => thresholdQuery.refetch() });
  const [thresholdDraft, setThresholdDraft] = useState<number | null>(null);
  const summary = query.data?.summary;
  const configuredThreshold = thresholdDraft ?? thresholdQuery.data?.threshold ?? 20;
  const failureRate = summary?.total ? (summary.failed / summary.total) * 100 : 0;
  const highFailureRate = (summary?.failed ?? 0) >= 3 && failureRate >= configuredThreshold;
  const exportRows = () => rows.map((row) => ({ "التاريخ": new Date(row.createdAt).toLocaleString("ar-SA"), "المستخدم": row.actorName, "التقرير": row.report, "الصيغة": formatLabels[row.format] ?? row.format, "النتيجة": statusLabels[row.status] ?? row.status, "عدد الصفوف": row.rowCount, "التفاصيل": row.error || "—" }));
  const exportExcel = async () => { await authorizeExport.mutateAsync(); exportLog.mutate({ format: "excel", report: "سجل عمليات التصدير", rowCount: rows.length, status: "started", filters: { format, status, actorQuery, from, to } }); try { const workbook = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(workbook, XLSX.utils.json_to_sheet(exportRows()), "سجل التصدير"); XLSX.writeFile(workbook, `سجل-عمليات-التصدير-${from || "كل"}-${to || "الفترة"}.xlsx`); exportLog.mutate({ format: "excel", report: "سجل عمليات التصدير", rowCount: rows.length, status: "success", filters: { format, status, actorQuery, from, to } }); } catch (error) { exportLog.mutate({ format: "excel", report: "سجل عمليات التصدير", rowCount: rows.length, status: "failed", error: error instanceof Error ? error.message : String(error), filters: { format, status, actorQuery, from, to } }); throw error; } };
  const exportStatistics = async () => { await authorizeExport.mutateAsync(); exportLog.mutate({ format: "excel", report: "إحصاءات سجل عمليات التصدير", rowCount: 1, status: "started", filters: { format, status, actorQuery, from, to } }); try { const statistics = [{ "الفترة": `${from || "كل"} - ${to || "الفترة"}`, "إجمالي العمليات": summary?.total ?? 0, "الناجحة": summary?.success ?? 0, "الفاشلة": summary?.failed ?? 0, "بدأت ولم تحسم": summary?.started ?? 0, "نسبة النجاح": `${summary?.successRate ?? 0}%`, "نسبة الفشل": `${failureRate.toFixed(1)}%` }]; const workbook = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(workbook, XLSX.utils.json_to_sheet(statistics), "الإحصاءات"); XLSX.writeFile(workbook, `إحصاءات-سجل-التصديرات-${from || "كل"}-${to || "الفترة"}.xlsx`); exportLog.mutate({ format: "excel", report: "إحصاءات سجل عمليات التصدير", rowCount: 1, status: "success", filters: { format, status, actorQuery, from, to } }); } catch (error) { exportLog.mutate({ format: "excel", report: "إحصاءات سجل عمليات التصدير", rowCount: 1, status: "failed", error: error instanceof Error ? error.message : String(error), filters: { format, status, actorQuery, from, to } }); throw error; } };
  const exportPdf = async () => { await authorizeExport.mutateAsync(); exportLog.mutate({ format: "pdf", report: "سجل عمليات التصدير", rowCount: rows.length, status: "started", filters: { format, status, actorQuery, from, to } }); try { const doc = new jsPDF({ orientation: "landscape", unit: "pt", format: "a4" }); doc.setFontSize(16); doc.text("Export Operations Audit", 40, 42); doc.setFontSize(9); doc.text(`Filters: ${format}/${status} | ${from || "all"} - ${to || "all"}`, 40, 60); let y = 84; exportRows().slice(0, 32).forEach((row, index) => { doc.text(`${index + 1}. ${String(row["التاريخ"])} | ${String(row["المستخدم"])} | ${String(row["الصيغة"])} | ${String(row["النتيجة"])} | ${String(row["عدد الصفوف"])}`, 40, y); y += 16; }); doc.save(`سجل-عمليات-التصدير-${from || "كل"}-${to || "الفترة"}.pdf`); exportLog.mutate({ format: "pdf", report: "سجل عمليات التصدير", rowCount: rows.length, status: "success", filters: { format, status, actorQuery, from, to } }); } catch (error) { exportLog.mutate({ format: "pdf", report: "سجل عمليات التصدير", rowCount: rows.length, status: "failed", error: error instanceof Error ? error.message : String(error), filters: { format, status, actorQuery, from, to } }); throw error; } };

  return <div className="space-y-4" dir="rtl">
    <Card className="border-border bg-card shadow-sm"><CardHeader className="pb-3"><div className="flex flex-wrap items-start justify-between gap-3"><div><CardTitle className="flex items-center gap-2 text-lg"><Download className="h-5 w-5 text-emerald-600" /> سجل عمليات التصدير</CardTitle><p className="mt-1 text-xs text-muted-foreground">تتبع محاولات التصدير ونتائجها مع اسم المستخدم وعدد الصفوف والفلاتر المستخدمة.</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" className="rounded-xl" onClick={exportExcel} disabled={!rows.length || !canExport.data || authorizeExport.isPending}><Download className="ml-2 h-4 w-4" /> Excel</Button><Button variant="outline" className="rounded-xl" onClick={exportPdf} disabled={!rows.length || !canExport.data || authorizeExport.isPending}><FileText className="ml-2 h-4 w-4" /> PDF</Button><Button variant="outline" className="rounded-xl" onClick={exportStatistics} disabled={!canExport.data || authorizeExport.isPending}><Download className="ml-2 h-4 w-4" /> إحصاءات Excel</Button><Button variant="outline" className="rounded-xl" onClick={() => query.refetch()} disabled={query.isFetching}><RefreshCw className={`ml-2 h-4 w-4 ${query.isFetching ? "animate-spin" : ""}`} /> تحديث</Button></div></div></CardHeader><CardContent>
      <div className="grid gap-3 md:grid-cols-2 lg:grid-cols-5"><label className="text-xs text-muted-foreground">الصيغة<select value={format} onChange={(e) => setFormat(e.target.value)} className="mt-1 h-10 w-full rounded-xl border border-input bg-background px-3 text-sm text-foreground"><option value="all">كل الصيغ</option><option value="csv">CSV</option><option value="excel">Excel</option><option value="pdf">PDF</option></select></label><label className="text-xs text-muted-foreground">النتيجة<select value={status} onChange={(e) => setStatus(e.target.value)} className="mt-1 h-10 w-full rounded-xl border border-input bg-background px-3 text-sm text-foreground"><option value="all">كل النتائج</option><option value="started">بدأت</option><option value="success">نجحت</option><option value="failed">فشلت</option></select></label><label className="text-xs text-muted-foreground">المستخدم<div className="relative mt-1"><Search className="pointer-events-none absolute right-3 top-3 h-4 w-4 text-muted-foreground" /><Input value={actorQuery} onChange={(e) => setActorQuery(e.target.value)} placeholder="اسم أو بريد المستخدم" className="rounded-xl pr-9" /></div></label><label className="text-xs text-muted-foreground">من<input type="date" value={from} onChange={(e) => setFrom(e.target.value)} className="mt-1 h-10 w-full rounded-xl border border-input bg-background px-3 text-sm text-foreground" /></label><label className="text-xs text-muted-foreground">إلى<input type="date" value={to} onChange={(e) => setTo(e.target.value)} className="mt-1 h-10 w-full rounded-xl border border-input bg-background px-3 text-sm text-foreground" /></label></div>{canExport.data === false && <p className="mt-2 text-xs text-rose-600">ليس لديك صلاحية تصدير سجل العمليات. يمكن لمدير النظام منحها من إدارة الحسابات.</p>}
      {canExport.data && <div className="mt-4 flex flex-wrap items-end gap-2 rounded-xl border border-border bg-muted/30 p-3"><label className="text-xs text-muted-foreground">حد تنبيه فشل التصدير (%)<input type="number" min={1} max={100} value={configuredThreshold} onChange={(event) => setThresholdDraft(Math.min(100, Math.max(1, Number(event.target.value) || 1)))} className="mt-1 h-9 w-28 rounded-lg border border-input bg-background px-3 text-sm text-foreground" /></label><Button variant="outline" className="rounded-xl" disabled={saveThreshold.isPending || thresholdDraft === null || thresholdDraft === thresholdQuery.data?.threshold} onClick={() => thresholdDraft !== null && saveThreshold.mutate({ threshold: thresholdDraft })}>{saveThreshold.isPending ? "جارٍ الحفظ…" : "حفظ الحد"}</Button><span className="text-[11px] text-muted-foreground">يُرسل النظام تنبيهًا للمشرف عند تجاوز الحد في آخر 100 عملية، مع منع تكرار التنبيه خلال 24 ساعة.</span></div>}
      {highFailureRate && <div role="alert" className="mt-4 flex items-start gap-2 rounded-xl border border-rose-200 bg-rose-50 p-3 text-xs text-rose-800 dark:border-rose-900/60 dark:bg-rose-950/30 dark:text-rose-200"><AlertTriangle className="mt-0.5 h-4 w-4 shrink-0" /><div><p className="font-semibold">تنبيه: ارتفاع معدل فشل التصدير</p><p className="mt-1">بلغت نسبة العمليات الفاشلة {failureRate.toFixed(1)}% ({summary?.failed ?? 0} عمليات)، وهي أعلى من الحد المضبوط {configuredThreshold}%. راجع سجل الأخطاء والصلاحيات قبل مشاركة التقارير.</p></div></div>}
      <div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><div className="rounded-xl bg-muted/50 p-3"><p className="text-[11px] text-muted-foreground">إجمالي العمليات</p><p className="mt-1 text-xl font-bold text-foreground">{query.data?.summary?.total ?? 0}</p></div><div className="rounded-xl bg-emerald-50 p-3 dark:bg-emerald-950/30"><p className="text-[11px] text-muted-foreground">ناجحة</p><p className="mt-1 text-xl font-bold text-emerald-700 dark:text-emerald-300">{query.data?.summary?.success ?? 0}</p></div><div className="rounded-xl bg-rose-50 p-3 dark:bg-rose-950/30"><p className="text-[11px] text-muted-foreground">فاشلة</p><p className="mt-1 text-xl font-bold text-rose-700 dark:text-rose-300">{query.data?.summary?.failed ?? 0}</p></div><div className="rounded-xl bg-amber-50 p-3 dark:bg-amber-950/30"><p className="text-[11px] text-muted-foreground">بدأت ولم تُحسم</p><p className="mt-1 text-xl font-bold text-amber-700 dark:text-amber-300">{query.data?.summary?.started ?? 0}</p></div><div className="rounded-xl bg-blue-50 p-3 dark:bg-blue-950/30"><p className="text-[11px] text-muted-foreground">نسبة النجاح</p><p className="mt-1 text-xl font-bold text-blue-700 dark:text-blue-300">{query.data?.summary?.successRate ?? 0}%</p></div></div>
      <div className="mt-4 flex items-center gap-2 text-xs text-muted-foreground"><Filter className="h-4 w-4" /> عرض {rows.length} من أصل {query.data?.total ?? 0} عملية</div>
      <div className="mt-3 overflow-x-auto rounded-xl border border-border"><table className="w-full min-w-[760px] text-right text-xs"><thead className="bg-muted/60 text-muted-foreground"><tr><th className="p-3">التاريخ</th><th className="p-3">المستخدم</th><th className="p-3">التقرير</th><th className="p-3">الصيغة</th><th className="p-3">النتيجة</th><th className="p-3">الصفوف</th><th className="p-3">التفاصيل</th></tr></thead><tbody>{query.isLoading ? <tr><td colSpan={7} className="p-8 text-center text-muted-foreground">جارٍ تحميل سجل التصديرات…</td></tr> : rows.length ? rows.map((row) => <tr key={row.id} className="border-t border-border"><td className="p-3 whitespace-nowrap">{new Date(row.createdAt).toLocaleString("ar-SA")}</td><td className="p-3">{row.actorName}</td><td className="p-3">{row.report}</td><td className="p-3"><Badge variant="outline" className="rounded-full">{formatLabels[row.format] ?? row.format}</Badge></td><td className="p-3"><Badge className={`rounded-full ${row.status === "success" ? "bg-emerald-600" : row.status === "failed" ? "bg-rose-600" : "bg-amber-600"}`}>{statusLabels[row.status] ?? row.status}</Badge></td><td className="p-3">{row.rowCount.toLocaleString("ar-SA")}</td><td className="max-w-[220px] truncate p-3 text-rose-700" title={row.error || undefined}>{row.error || "—"}</td></tr>) : <tr><td colSpan={7} className="p-8 text-center text-muted-foreground">لا توجد عمليات تصدير مطابقة للفلاتر الحالية.</td></tr>}</tbody></table></div>
      {query.error && <p className="mt-3 text-xs text-rose-600">تعذر تحميل السجل: {query.error.message}</p>}
    </CardContent></Card>
  </div>;
}
