import { useEffect, useMemo, useState } from "react";
import { ArrowDownLeft, Download, Eye, FileImage, FileText, History, Share2, TrendingDown, TrendingUp } from "lucide-react";
import { Bar, BarChart, CartesianGrid, Legend, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import * as XLSX from "xlsx";
import jsPDF from "jspdf";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";

type Branch = { id: number; code?: string | number | null; name: string; area?: string | null; revenue?: number | null; netProfit?: number | null; sales?: number | null; operationalType?: string | null };
type Summary = { currentPeriod?: string | null; previousPeriod?: string | null; currentSales?: number; previousSales?: number; salesChangePercent?: number | null; priorYearPeriod?: string | null; priorYearSales?: number; yearOverYearChangePercent?: number | null; staleCount?: number; lowStockCount?: number };
type ReportRecord = { id: string; createdAt: string; branchNames: string[]; selectedCount: number; period: string; fileName: string };
type Props = { branches: Branch[]; summary?: Summary | null; onOpenInventory: () => void; onOpenBranches: () => void };

const money = (value: number) => `${value.toLocaleString("ar-SA", { maximumFractionDigits: 0 })} ر.س`;
const pct = (current: number, previous: number) => previous ? ((current - previous) / Math.abs(previous)) * 100 : null;
const REPORTS_KEY = "branch-ops-comparison-reports";

export function SmartBranchComparison({ branches, summary, onOpenInventory, onOpenBranches }: Props) {
  const [selectedIds, setSelectedIds] = useState<number[]>(() => branches.slice(0, 5).map((branch) => branch.id));
  const [reports, setReports] = useState<ReportRecord[]>(() => { try { return JSON.parse(localStorage.getItem(REPORTS_KEY) ?? "[]"); } catch { return []; } });
  const [rangeStart, setRangeStart] = useState("");
  const [rangeEnd, setRangeEnd] = useState("");
  const [previewType, setPreviewType] = useState<"pdf" | "excel" | null>(null);
  const [centerFilter, setCenterFilter] = useState<"all" | "sales" | "nonSales">("all");
  const shareLogQuery = trpc.reportShares.list.useQuery(undefined, { staleTime: 30_000 });
  const filteredBranches = useMemo(() => branches.filter((branch) => centerFilter === "all" || (centerFilter === "sales" ? (branch.operationalType === "branch" || branch.operationalType === "فرع") : !(branch.operationalType === "branch" || branch.operationalType === "فرع"))), [branches, centerFilter]);
  const selected = useMemo(() => filteredBranches.filter((branch) => selectedIds.includes(branch.id)), [filteredBranches, selectedIds]);
  useEffect(() => setSelectedIds((ids) => ids.filter((id) => branches.some((branch) => branch.id === id))), [branches]);
  useEffect(() => localStorage.setItem(REPORTS_KEY, JSON.stringify(reports.slice(0, 20))), [reports]);
  const currentSales = Number(summary?.currentSales ?? 0); const previousSales = Number(summary?.previousSales ?? 0); const change = summary?.salesChangePercent ?? pct(currentSales, previousSales); const priorYearSales = Number(summary?.priorYearSales ?? 0);
  const chartData = [{ period: summary?.priorYearPeriod ?? "نفس الشهر العام الماضي", sales: priorYearSales }, { period: summary?.previousPeriod ?? "السابق", sales: previousSales }, { period: summary?.currentPeriod ?? "الحالي", sales: currentSales }];
  const toggle = (id: number) => setSelectedIds((ids) => ids.includes(id) ? ids.filter((item) => item !== id) : [...ids, id]);
  const customRange = rangeStart && rangeEnd ? `${rangeStart} إلى ${rangeEnd}` : rangeStart || rangeEnd ? `${rangeStart || "بداية الفترة"} إلى ${rangeEnd || "نهاية الفترة"}` : "الفترة الافتراضية";
  const rangeValid = !rangeStart || !rangeEnd || rangeStart <= rangeEnd;
  const remember = (fileName: string) => setReports((items) => [{ id: crypto.randomUUID(), createdAt: new Date().toISOString(), branchNames: selected.map((branch) => branch.name), selectedCount: selected.length, period: customRange, fileName }, ...items].slice(0, 20));
  const exportWorkbook = () => { if (!rangeValid) return; const rows = selected.map((branch) => ({ الفرع: branch.name, الرمز: branch.code ?? "—", المنطقة: branch.area ?? "—", المبيعات: Number(branch.revenue ?? branch.sales ?? 0), صافي_الربح: Number(branch.netProfit ?? 0) })); const workbook = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(workbook, XLSX.utils.json_to_sheet([{ نطاق_التقرير: customRange }, ...rows]), "الفروع المحددة"); XLSX.utils.book_append_sheet(workbook, XLSX.utils.json_to_sheet(chartData.map((item) => ({ الفترة: item.period, المبيعات: item.sales, نطاق_التقرير: customRange }))), "المقارنة الزمنية"); const fileName = `تقرير-مقارنة-الفروع-${rangeStart || "الفترة"}-${rangeEnd || "الحالية"}.xlsx`; XLSX.writeFile(workbook, fileName); remember(fileName); };
  const previewRows = selected.map((branch) => ({ name: branch.name, code: branch.code ?? "—", sales: Number(branch.revenue ?? branch.sales ?? 0), profit: Number(branch.netProfit ?? 0) }));
  const openPreview = (type: "pdf" | "excel") => { if (selected.length && rangeValid) setPreviewType(type); };
  const exportPdf = () => { if (!rangeValid) return; const doc = new jsPDF({ orientation: "landscape" }); doc.setFont("helvetica", "bold"); doc.setFontSize(18); doc.text("Branch comparison report", 280, 18, { align: "right" }); doc.setFontSize(11); doc.text(`Selected branches: ${selected.length}`, 280, 28, { align: "right" }); doc.text(`Custom range: ${customRange}`, 280, 35, { align: "right" }); selected.forEach((branch, index) => doc.text(`${index + 1}. ${branch.name} | Sales: ${Number(branch.revenue ?? branch.sales ?? 0).toLocaleString()} | Profit: ${Number(branch.netProfit ?? 0).toLocaleString()}`, 280, 47 + index * 9, { align: "right" })); doc.text(`Period change: ${change === null ? "N/A" : `${change.toFixed(1)}%`}`, 280, 57 + selected.length * 9, { align: "right" }); const fileName = `تقرير-مقارنة-الفروع-${rangeStart || "الفترة"}-${rangeEnd || "الحالية"}.pdf`; doc.save(fileName); remember(fileName); };
  const shareReport = async (report: ReportRecord) => { if (!navigator.share) return; const text = `تقرير مقارنة الفروع\n${report.branchNames.join("، ")}\n${report.period}`; await navigator.share({ title: "تقرير مقارنة الفروع", text }); };
  return <section className="mt-5 rounded-3xl border border-[#dfe9df] bg-white p-5 shadow-[0_5px_18px_rgba(39,70,48,0.04)]" aria-label="المقارنة الزمنية وتقرير الفروع الموحد">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-semibold text-[#4d8068]">مقارنة زمنية موحدة</p><h3 className="mt-1 text-lg font-bold">الحالي والسابق ونفس الشهر من العام الماضي</h3><p className="mt-1 text-xs">تقرير موحد للفروع والمراكز المتاحة حسب صلاحيات حسابك.</p></div><div className="flex flex-wrap items-center gap-2"><label className="text-[10px] text-[#6b8172]">نوع المركز<select value={centerFilter} onChange={(event) => setCenterFilter(event.target.value as "all" | "sales" | "nonSales")} className="mr-1 h-9 rounded-xl border border-[#dce5dc] bg-white px-2 text-xs"><option value="all">الكل</option><option value="sales">المراكز البيعية فقط</option><option value="nonSales">المراكز غير البيعية</option></select></label><Button variant="outline" size="sm" className="rounded-xl text-xs" onClick={() => openPreview("excel")} disabled={!selected.length || !rangeValid}><Eye className="ml-1 h-3.5 w-3.5" /> معاينة Excel</Button><Button variant="outline" size="sm" className="rounded-xl text-xs" onClick={() => openPreview("pdf")} disabled={!selected.length || !rangeValid}><Eye className="ml-1 h-3.5 w-3.5" /> معاينة PDF</Button><Button variant="outline" size="sm" className="rounded-xl text-xs" onClick={onOpenInventory}><FileImage className="ml-1 h-3.5 w-3.5" /> الرسوم التفصيلية</Button></div></div><div className="mt-3 rounded-2xl border border-[#e5eee6] bg-[#f8fbf8] p-3"><p className="text-xs font-semibold text-[#315542]">نطاق التقرير التجريبي</p><div className="mt-2 grid gap-2 sm:grid-cols-2"><label className="text-[10px] text-[#6b8172]">من<Input type="date" value={rangeStart} onChange={(event) => setRangeStart(event.target.value)} className="mt-1 h-9 rounded-xl bg-white text-xs" /></label><label className="text-[10px] text-[#6b8172]">إلى<Input type="date" value={rangeEnd} onChange={(event) => setRangeEnd(event.target.value)} className="mt-1 h-9 rounded-xl bg-white text-xs" /></label></div>{!rangeValid && <p className="mt-2 text-[10px] text-[#b95e55]">يجب أن يكون تاريخ البداية قبل تاريخ النهاية.</p>}<p className="mt-2 text-[10px] text-[#89948b]">يُدرج النطاق في ترويسة التقرير وورقة البيانات لتسهيل مراجعة بيانات TEST_DATA.</p></div>
    <div className="mt-4 grid gap-4 lg:grid-cols-[1fr_300px]"><div className="h-56"><ResponsiveContainer width="100%" height="100%"><BarChart data={chartData} margin={{ top: 8, right: 8, left: 8, bottom: 8 }}><CartesianGrid strokeDasharray="3 3" stroke="#e8efe8" /><XAxis dataKey="period" tick={{ fontSize: 11 }} /><YAxis tick={{ fontSize: 10 }} tickFormatter={(value) => `${Number(value).toLocaleString("ar-SA")}`} /><Tooltip formatter={(value) => [money(Number(value)), "صافي المبيعات"]} /><Legend /><Bar dataKey="sales" name="صافي المبيعات" fill="#4d9b70" radius={[6, 6, 0, 0]} /></BarChart></ResponsiveContainer></div><div className="rounded-2xl bg-[#f1f8f2] p-4"><p className="text-[10px] text-[#89948b]">نسبة التغير الشهري</p><div className="mt-2 flex items-center gap-2">{change !== null && (change >= 0 ? <TrendingUp className="h-5 w-5 text-[#2d7d58]" /> : <TrendingDown className="h-5 w-5 text-[#b95e55]" />)}<p className={`text-2xl font-bold ${change === null || change >= 0 ? "text-[#2d7d58]" : "text-[#b95e55]"}`}>{change === null ? "—" : `${change >= 0 ? "+" : ""}${change.toFixed(1)}%`}</p></div><p className="mt-2 text-[10px] text-[#6b8172]">{money(currentSales)} حاليًا · {money(previousSales)} سابقًا · {money(priorYearSales)} سنويًا</p><p className={`mt-2 text-xs font-semibold ${summary?.yearOverYearChangePercent == null || summary.yearOverYearChangePercent >= 0 ? "text-[#2d7d58]" : "text-[#b95e55]"}`}>التغير السنوي: {summary?.yearOverYearChangePercent == null ? "—" : `${summary.yearOverYearChangePercent >= 0 ? "+" : ""}${summary.yearOverYearChangePercent.toFixed(1)}%`}</p><button type="button" className="mt-4 inline-flex items-center text-[11px] font-semibold text-[#315542]" onClick={onOpenInventory}>افتح التحليل التفصيلي <ArrowDownLeft className="mr-1 h-3.5 w-3.5" /></button></div></div>
    <div className="mt-4 rounded-2xl border border-[#edf1ed] bg-[#fbfdfb] p-3"><div className="flex items-center justify-between gap-2"><div><p className="text-xs font-semibold text-[#315542]">الفروع المشمولة في التقرير الموحد</p><p className="mt-1 text-[10px] text-[#89948b]">تظهر هنا الفروع المسموح لك بالوصول إليها فقط.</p></div><button type="button" className="text-[10px] font-semibold text-[#4d8068]" onClick={() => setSelectedIds(filteredBranches.map((branch) => branch.id))}>تحديد الكل</button></div><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{filteredBranches.map((branch) => <label key={branch.id} className={`flex cursor-pointer items-center gap-2 rounded-xl border p-2 text-xs transition-colors ${selectedIds.includes(branch.id) ? "border-[#9bc6a8] bg-[#eef8f0]" : "border-[#edf1ed] bg-white"}`}><input type="checkbox" checked={selectedIds.includes(branch.id)} onChange={() => toggle(branch.id)} className="accent-[#4d8068]" /><span className="truncate">{branch.name}</span></label>)}</div><button type="button" className="mt-3 inline-flex items-center text-[11px] font-semibold text-[#315542]" onClick={onOpenBranches}>إدارة قائمة الفروع <ArrowDownLeft className="mr-1 h-3.5 w-3.5" /></button></div>
    <div className="mt-4 rounded-2xl border border-[#edf1ed] bg-white p-3"><div className="flex items-center justify-between gap-2"><div className="flex items-center gap-2"><History className="h-4 w-4 text-[#4d8068]" /><p className="text-xs font-semibold text-[#315542]">سجل التقارير المجمعة</p></div><span className="text-[10px] text-[#89948b]">{shareLogQuery.data?.length ?? 0} مشاركة مركزية</span></div>{reports.length ? <div className="mt-3 space-y-2">{reports.slice(0, 5).map((report) => <div key={report.id} className="flex flex-wrap items-center justify-between gap-2 rounded-xl bg-[#f8fbf8] px-3 py-2 text-[10px]"><span className="min-w-0 flex-1 truncate text-[#526359]">{report.fileName} · {report.selectedCount} فروع · {new Date(report.createdAt).toLocaleString("ar-SA")}</span><div className="flex gap-1"><button type="button" className="rounded-lg p-1.5 text-[#4d8068] hover:bg-[#eaf4eb]" title="إعادة إنشاء التقرير" onClick={report.fileName.endsWith(".pdf") ? exportPdf : exportWorkbook}><Download className="h-3.5 w-3.5" /></button><button type="button" className="rounded-lg p-1.5 text-[#4d8068] hover:bg-[#eaf4eb]" title="مشاركة" onClick={() => void shareReport(report)}><Share2 className="h-3.5 w-3.5" /></button></div></div>)}</div> : <p className="mt-2 text-[10px] text-[#89948b]">ستظهر التقارير هنا بعد أول تصدير.</p>}{shareLogQuery.data?.length ? <div className="mt-3 border-t border-[#edf1ed] pt-3"><p className="text-[10px] font-semibold text-[#526359]">آخر حالات المشاركة</p><div className="mt-2 space-y-1">{shareLogQuery.data.slice(0, 3).map((entry) => <div key={entry.id} className="flex items-center justify-between gap-2 rounded-lg bg-[#fbfdfb] px-2 py-1.5 text-[10px]"><span className="truncate text-[#6b8172]">تقرير #{entry.reportId} · {entry.channel}</span><span className={entry.status === "sent" ? "font-semibold text-[#2d7d58]" : entry.status === "failed" ? "font-semibold text-[#b95e55]" : "text-[#a47732]"}>{entry.status === "sent" ? "تم الإرسال" : entry.status === "failed" ? "فشل" : entry.status === "partial" ? "جزئي" : "قيد الانتظار"}</span></div>)}</div></div> : null}</div>
    <Dialog open={previewType !== null} onOpenChange={(open) => !open && setPreviewType(null)}><DialogContent dir="rtl" className="max-w-2xl"><DialogHeader><DialogTitle>معاينة تقرير {previewType === "pdf" ? "PDF" : "Excel"} قبل التصدير</DialogTitle></DialogHeader><div className="space-y-3 text-xs"><div className="rounded-xl bg-[#f8fbf8] p-3"><p className="font-semibold text-[#315542]">النطاق: {customRange}</p><p className="mt-1 text-[#6b8172]">عدد الفروع: {selected.length} · سيتم تصدير البيانات المحددة فقط.</p></div><div className="max-h-72 overflow-auto rounded-xl border border-[#e5eee6]"><table className="w-full text-right"><thead className="bg-[#f8fbf8]"><tr><th className="p-2">الفرع</th><th className="p-2">الرمز</th><th className="p-2">المبيعات</th><th className="p-2">صافي الربح</th></tr></thead><tbody>{previewRows.map((row) => <tr key={row.name} className="border-t border-[#edf1ed]"><td className="p-2">{row.name}</td><td className="p-2">{row.code}</td><td className="p-2">{money(row.sales)}</td><td className="p-2">{money(row.profit)}</td></tr>)}</tbody></table></div><p className="text-[10px] text-[#89948b]">راجع الفروع والنطاق قبل التأكيد. لا يتم إنشاء ملف أو تسجيل تقرير حتى الضغط على زر التصدير.</p></div><DialogFooter><Button variant="outline" className="rounded-xl" onClick={() => setPreviewType(null)}>إلغاء</Button><Button className="rounded-xl bg-[#17624b]" onClick={() => { setPreviewType(null); if (previewType === "pdf") exportPdf(); else exportWorkbook(); }}><Download className="ml-1 h-3.5 w-3.5" /> تأكيد تصدير {previewType === "pdf" ? "PDF" : "Excel"}</Button></DialogFooter></DialogContent></Dialog>
  </section>;
}
